version: "3"
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        ports:
            - 80:80
            - 443:443
    fpm:
        container_name: phpfpm
        build: docker/php-fpm
        volumes:
            - ./:/var/www/html
    mysql:
        container_name: mysql8
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
            - /var/lib/mysql
        ports:
            - 3306:3306
    mailpit:
        container_name: mailpit
        image: axllent/mailpit
        restart: always
        ports:
            - 1025:1025
            - 8025:8025
